name: "Hello Github Actions"
description: "This is Github Actions"

on:
  workflow_dispatch:

jobs:
  Hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: "say Hello"
        run: echo "Hello From GitHub Actions"
